export function getSkillTemplate(): string {
   return [
      "# SKILL.md — AgentFoundry Orchestration Skill",
      "",
      "## Purpose",
      "",
      "Use AgentFoundry for complex coding work that benefits from explicit planning, ordered task execution, and verification gates.",
      "",
      "## Route to AgentFoundry when",
      "",
      "- The user asks for multi-step implementation work.",
      "- The request touches multiple files, systems, or phases.",
      "- The task needs strict sequencing, retries, or progress tracking.",
      "- Verification (build/test checks) is required before completion.",
      "",
      "## Do NOT route when",
      "",
      "- The task is a small single-file change.",
      "- The user asks a quick conceptual question only.",
      "- The request is a trivial edit that can be done directly.",
      "",
      "## Required execution loop",
      "",
      "1. Call `agentfoundry_submit_plan`",
      "   with:",
      "   - `prompt`: original user goal",
      "   - `planSummary`: concise but durable narrative for cross-turn/client handoff",
      "   - optional `risks` and `discrepancies`",
      "2. Call `agentfoundry_add_tasks_and_start`",
      "   with:",
      "   - `runId` from step 1",
      "   - ordered atomic `tasks` array with required `verificationCommands` on every task",
      "3. Loop:",
      "   - `agentfoundry_claim_next_task`",
      "   - execute task with available coding tools",
      "   - `agentfoundry_submit_task_result`",
      "   - stop when `claimed: false`",
      "",
      "## Context continuity rules",
      "",
      "- Keep a stable `runId` and do not re-plan unless requirements changed.",
      "- Write plan summaries and task descriptions so another client can continue without extra explanation.",
      "- On client switch, start with `agentfoundry_status` and resume the same queue.",
      "- Keep tasks small enough that verification output is easy to interpret.",
      "",
      "## Task authoring rules",
      "",
      "- Keep each task atomic and independently verifiable.",
      "- Use imperative task titles (e.g., \"Add API validation for run status route\").",
      "- Include concrete acceptance criteria.",
      "- Include required repository-specific verification commands (never assume npm).",
      "- Keep task order dependency-safe (later tasks depend on earlier ones).",
      "",
      "## Error handling",
      "",
      "- If verification fails, inspect diagnostics from `agentfoundry_status`.",
      "- Use `agentfoundry_retry_task` for recoverable failures.",
      "- Use `agentfoundry_fail_task` with a specific reason when blocked.",
      "- Use `agentfoundry_heartbeat_lease` for long-running tasks.",
      "",
      "## User-facing reporting format",
      "",
      "At meaningful milestones, report:",
      "- run id",
      "- completed / failed counts",
      "- current task",
      "- next action",
      "",
      "Keep updates concise and action-oriented.",
      ""
   ].join("\n");
}
